site_name: My Docs
site_url: https://NetworkingB2A.github.io/Portfolio
nav:
    - Home: index.md
    - Markdown Tips: ../markdown_tips.md
    - Networking: Networking/VxLAN.md
theme: readthedocs
plugins:
  - search:
      lang: en