site_name: Training
site_url: https://NetworkingB2A.github.io/Portfolio
#theme: readthedocs
theme: 
    name: material
    features:
        - navigation.tabs
        - navigation.sections
        - toc.integrate
        - search.suggest
        - search.highlight
        - content.tabs.link
        - content.code.annotate
        - content.code.copy
    language: en
plugins:
  - search:
      lang: en